import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio - Thomas Henningson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex landscape:flex-col min-h-screen p-8">
          <Navbar />
          <main className="flex-grow mt-2 ml-2">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
